#!/usr/bin/env python3
"""Verify the VCR chain and H5/E5 replay closure without network access.

The released records are verified against PUBLIC_RECORD_MANIFEST.jsonl, while
hashes of task, prompt, request, and parsed objects are recomputed in place.
Provider responses are never regenerated: saved responses are the VCR inputs.
All deterministic replay, scoring, comparisons, and tables are regenerated by
RUN_ALL_OFFLINE.py before this verifier is called.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
from collections import Counter
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
WORKSPACE = ROOT / "frozen_inputs/project"
EXPECTED = ROOT / "VCR_H5E5_EXPECTED.json"

DATASETS = {
    "E1": WORKSPACE / "runs/experiments_v2/e1/e1_20260801T044500Z/records",
    "E2": WORKSPACE / "runs/experiments_v2/e2/e2_20260801T054708Z/records",
    "F1": WORKSPACE
    / "segan_revision_major_v2/runs/e2b_protocol_v2/e2b_v2_f1_20260813/records",
    "F0": WORKSPACE
    / "segan_revision_major_v2/runs/f0_formal_v1/f0_formal_20260820T_authorized_v1/records",
    "QWEN37": WORKSPACE
    / "segan_revision_major_v2/runs/qwen37plus_f1f0_v1/qwen37plus_formal_20260826T/records",
}


def canonical_bytes(value: Any) -> bytes:
    return json.dumps(
        value, ensure_ascii=False, sort_keys=True, separators=(",", ":")
    ).encode("utf-8")


def digest(value: Any) -> str:
    return hashlib.sha256(canonical_bytes(value)).hexdigest()


def digest_text(value: str) -> str:
    return hashlib.sha256(value.encode("utf-8")).hexdigest()


def digest_file(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def load(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def load_records(directory: Path) -> list[tuple[Path, dict[str, Any]]]:
    return [(path, load(path)) for path in sorted(directory.glob("*.json"))]


def require(condition: bool, code: str, errors: list[str]) -> None:
    if not condition:
        errors.append(code)


def timestamp_complete(response: dict[str, Any]) -> bool:
    attempts = response.get("attempts", [])
    if response.get("status") == "skipped":
        return not attempts
    if not attempts:
        return False
    return all(
        isinstance(item, dict)
        and bool(item.get("request_sent_utc"))
        and bool(item.get("response_received_utc"))
        for item in attempts
    )


def action_energy(action: Any) -> float | None:
    if not isinstance(action, list):
        return None
    try:
        return 0.25 * sum(abs(float(value)) for value in action)
    except (TypeError, ValueError):
        return None


def verify_release_map(
    all_files: dict[str, Path], errors: list[str]
) -> dict[str, int]:
    map_path = ROOT / "manifests/PUBLIC_RECORD_MANIFEST.jsonl"
    rows = [
        json.loads(line)
        for line in map_path.read_text(encoding="utf-8").splitlines()
        if line.strip()
    ]
    seen: set[str] = set()
    for row in rows:
        name = Path(str(row["path"])).name
        require(name not in seen, f"duplicate_release_map_name:{name}", errors)
        seen.add(name)
        path = all_files.get(name)
        require(path is not None, f"release_map_missing_file:{name}", errors)
        if path is not None:
            require(
                digest_file(path) == row["sha256"],
                f"release_hash_mismatch:{name}",
                errors,
            )
    require(set(all_files) == seen, "release_map_population_mismatch", errors)
    return {"rows": len(rows), "unique_release_files": len(seen)}


def verify_e1(
    records: list[tuple[Path, dict[str, Any]]], errors: list[str]
) -> dict[str, int]:
    calls = 0
    timestamps = 0
    parsed_actions = 0
    energy_matches = 0
    for path, record in records:
        rid = str(record.get("episode_id", path.stem))
        require(digest(record.get("task")) == record.get("task_sha256"), f"E1_task:{rid}", errors)
        for stage_name in ("stage1", "stage2"):
            stage = record.get(stage_name, {})
            require(
                digest_text(str(stage.get("prompt", ""))) == stage.get("prompt_sha256"),
                f"E1_prompt:{rid}:{stage_name}",
                errors,
            )
            require(
                digest(stage.get("request")) == stage.get("request_sha256"),
                f"E1_request:{rid}:{stage_name}",
                errors,
            )
            require(
                digest(stage.get("parsed")) == stage.get("parsed_sha256"),
                f"E1_parsed:{rid}:{stage_name}",
                errors,
            )
            response = stage.get("response", {})
            require(isinstance(response.get("raw_response"), dict), f"E1_raw:{rid}:{stage_name}", errors)
            require(bool(stage.get("request_sent_utc")) and bool(stage.get("response_received_utc")), f"E1_timestamp:{rid}:{stage_name}", errors)
            calls += 1
            timestamps += int(bool(stage.get("request_sent_utc")) and bool(stage.get("response_received_utc")))
            parsed = stage.get("parsed", {})
            parsed_actions += int(isinstance(parsed.get("dense_action_kw"), list))
        outcome = record.get("outcome", {})
        if outcome.get("parser_success"):
            suffix = record["stage2"]["parsed"].get("dense_action_kw")
            prefix = record["stage1"]["parsed"].get("dense_action_kw")
            activation = record.get("canonical_context", {}).get("activation")
            candidates = [action_energy(suffix)]
            if (
                isinstance(prefix, list)
                and isinstance(suffix, list)
                and isinstance(activation, int)
                and len(suffix) == len(prefix) - activation
            ):
                candidates.append(action_energy(prefix[:activation] + suffix))
            saved = outcome.get("action_energy_kwh")
            ok = isinstance(saved, (int, float)) and any(
                value is not None and abs(value - float(saved)) <= 1e-6
                for value in candidates
            )
            require(ok, f"E1_action_energy:{rid}", errors)
            energy_matches += int(ok)
    return {
        "records": len(records),
        "planned_calls": calls,
        "timestamp_complete_calls": timestamps,
        "parsed_action_objects": parsed_actions,
        "replay_eligible_action_energy_matches": energy_matches,
    }


def verify_e2(
    records: list[tuple[Path, dict[str, Any]]], errors: list[str]
) -> dict[str, int]:
    branches = ("C", "M", "S", "K", "C2")
    planned = 0
    actual = 0
    skipped = 0
    timestamps = 0
    comparison_blocks = 0
    for path, record in records:
        rid = str(record.get("block_id", path.stem))
        require(digest(record.get("task")) == record.get("task_sha256"), f"E2_task:{rid}", errors)
        require(set(record.get("branches", {})) == set(branches), f"E2_branches:{rid}", errors)
        require(record.get("carriers", {}).get("C") == record.get("carriers", {}).get("C2"), f"E2_C_C2_carrier:{rid}", errors)
        require(record.get("branches", {}).get("C", {}).get("request_sha256") == record.get("branches", {}).get("C2", {}).get("request_sha256"), f"E2_C_C2_request:{rid}", errors)
        for stage_name, stage in [("stage1", record.get("stage1", {})), *[(name, record["branches"][name]) for name in branches]]:
            planned += 1
            response = stage.get("response", {})
            is_skipped = response.get("status") == "skipped"
            skipped += int(is_skipped)
            actual += int(not is_skipped)
            if is_skipped:
                require(stage.get("request") is None and stage.get("prompt") is None, f"E2_skip_contract:{rid}:{stage_name}", errors)
            else:
                require(digest_text(str(stage.get("prompt", ""))) == stage.get("prompt_sha256"), f"E2_prompt:{rid}:{stage_name}", errors)
                require(digest(stage.get("request")) == stage.get("request_sha256"), f"E2_request:{rid}:{stage_name}", errors)
                require(bool(stage.get("request_sent_utc")) and bool(stage.get("response_received_utc")), f"E2_timestamp:{rid}:{stage_name}", errors)
                raw_or_explicit_failure = isinstance(response.get("raw_response"), dict) or (
                    response.get("status") != "ok"
                    and bool(response.get("error_type"))
                    and response.get("content") == ""
                )
                require(raw_or_explicit_failure, f"E2_raw_or_failure:{rid}:{stage_name}", errors)
                timestamps += int(bool(stage.get("request_sent_utc")) and bool(stage.get("response_received_utc")))
            require(digest(stage.get("parsed")) == stage.get("parsed_sha256"), f"E2_parsed:{rid}:{stage_name}", errors)
        comparison_blocks += 1
    return {
        "records": len(records),
        "claim_bearing_branch_rows": len(records) * len(branches),
        "planned_calls": planned,
        "actual_calls": actual,
        "structured_skips": skipped,
        "timestamp_complete_actual_calls": timestamps,
        "comparison_blocks": comparison_blocks,
    }


def verify_four_branch(
    label: str,
    records: list[tuple[Path, dict[str, Any]]],
    tasks_by_scenario: dict[str, dict[str, Any]],
    errors: list[str],
) -> dict[str, int]:
    branches = ("C1", "C2", "S1", "S2")
    branch_rows = 0
    timestamps = 0
    byte_identity = 0
    replay_eligible = 0
    for path, record in records:
        rid = str(record.get("block_id", path.stem))
        scenario = str(record.get("scenario_id"))
        task = tasks_by_scenario.get(scenario)
        require(task is not None, f"{label}_task_join:{rid}", errors)
        if task is not None:
            require(digest(task) == record.get("task_sha256"), f"{label}_task_hash:{rid}", errors)
        require(set(record.get("branches", {})) == set(branches), f"{label}_branches:{rid}", errors)
        require(not record.get("protocol_exclusions"), f"{label}_protocol_exclusion:{rid}", errors)
        require(record.get("logical_provider_calls") == 4, f"{label}_logical_calls:{rid}", errors)
        for branch_name in branches:
            item = record["branches"][branch_name]
            require(digest(item.get("prompt_text")) == item.get("prompt_sha256"), f"{label}_prompt:{rid}:{branch_name}", errors)
            require(digest(item.get("request_payload")) == item.get("request_payload_bytes_sha256"), f"{label}_request:{rid}:{branch_name}", errors)
            response = item.get("response", {})
            require(response.get("status") == "ok", f"{label}_response:{rid}:{branch_name}", errors)
            require(isinstance(response.get("raw_response"), dict), f"{label}_raw:{rid}:{branch_name}", errors)
            complete = timestamp_complete(response)
            require(complete, f"{label}_timestamp:{rid}:{branch_name}", errors)
            timestamps += int(complete)
            parsed = item.get("parsed", {})
            require(isinstance(parsed.get("dense_action_kw"), list), f"{label}_parsed_action:{rid}:{branch_name}", errors)
            require(item.get("score") is not None, f"{label}_saved_score:{rid}:{branch_name}", errors)
            replay_eligible += int(parsed.get("ok") is True and item.get("score") is not None)
            branch_rows += 1
        same = (
            record["branches"]["C1"]["request_payload_bytes_sha256"]
            == record["branches"]["C2"]["request_payload_bytes_sha256"]
            and record["branches"]["S1"]["request_payload_bytes_sha256"]
            == record["branches"]["S2"]["request_payload_bytes_sha256"]
        )
        require(same, f"{label}_duplicate_request_identity:{rid}", errors)
        byte_identity += int(same)
    return {
        "records": len(records),
        "claim_bearing_branch_rows": branch_rows,
        "planned_and_actual_calls": branch_rows,
        "timestamp_complete_calls": timestamps,
        "duplicate_payload_identity_blocks": byte_identity,
        "replay_eligible_branch_rows": replay_eligible,
    }


def verify_comparison_csv(path: Path, errors: list[str]) -> dict[str, Any]:
    with path.open(encoding="utf-8", newline="") as handle:
        rows = list(csv.DictReader(handle))
    numeric = [
        "max_trace_abs_diff",
        "abs_diff_terminal_soc_kwh",
        "abs_diff_terminal_signed_error_kwh",
        "abs_diff_terminal_absolute_error_kwh",
        "abs_diff_total_violation_energy",
        "abs_diff_action_energy_kwh",
        "abs_diff_physical_cost_usd",
    ]
    flags = [
        "all_flag_matches",
        "match_dynamic_constraints_ok",
        "match_engineering_feasible",
        "match_strict_feasible",
        "match_violation_interval_count",
    ]
    maximum = max((abs(float(row[key])) for row in rows for key in numeric), default=0.0)
    bad_flags = sum(row[key] != "True" for row in rows for key in flags)
    require(maximum == 0.0, f"replay_numeric_difference:{path.name}:{maximum}", errors)
    require(bad_flags == 0, f"replay_flag_difference:{path.name}:{bad_flags}", errors)
    return {"rows": len(rows), "maximum_absolute_difference": maximum, "flag_mismatches": bad_flags}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--reproduced-root", type=Path, required=True)
    args = parser.parse_args()
    reproduced = args.reproduced_root.resolve()
    output = reproduced / "vcr_h5e5"
    errors: list[str] = []
    expected = load(EXPECTED)
    loaded = {name: load_records(path) for name, path in DATASETS.items()}
    all_files = {path.name: path for rows in loaded.values() for path, _ in rows}
    require(len(all_files) == sum(len(rows) for rows in loaded.values()), "duplicate_record_filename", errors)
    release_map = verify_release_map(all_files, errors)

    tasks_by_scenario: dict[str, dict[str, Any]] = {}
    for _, record in loaded["E2"]:
        tasks_by_scenario.setdefault(str(record["scenario_id"]), record["task"])

    populations = {
        "E1": verify_e1(loaded["E1"], errors),
        "E2": verify_e2(loaded["E2"], errors),
        "F1": verify_four_branch("F1", loaded["F1"], tasks_by_scenario, errors),
        "F0": verify_four_branch("F0", loaded["F0"], tasks_by_scenario, errors),
        "QWEN37": verify_four_branch("QWEN37", loaded["QWEN37"], tasks_by_scenario, errors),
    }

    comparisons = {
        "historical_F1_F0": verify_comparison_csv(
            reproduced / "primary/independent_replay_comparison.csv", errors
        ),
        "qwen37": verify_comparison_csv(
            reproduced / "qwen37/QWEN37_INDEPENDENT_REPLAY_COMPARISON.csv",
            errors,
        ),
    }
    physics = load(reproduced / "physics/INDEPENDENT_PHYSICS_CROSSCHECK.json")
    acceptance = load(reproduced / "acceptance/V1_7_RELEASE_ACCEPTANCE.json")
    parser_replay = load(reproduced / "parser/PARSER_REPLAY_VERIFICATION.json")
    require(physics.get("status") == "PASS", "independent_physics_status", errors)
    require(physics.get("rows") == expected["independent_physics_rows"], "independent_physics_rows", errors)
    require(physics.get("discrepancies") == 0, "independent_physics_discrepancies", errors)
    require(acceptance.get("status") == "PASS_WITH_BOUNDARIES", "release_acceptance_status", errors)
    require(parser_replay.get("status") == "PASS", "parser_replay_status", errors)
    require(parser_replay.get("successful_responses_reparsed") == 3526, "parser_replay_population", errors)
    require(parser_replay.get("parsed_object_mismatches") == 0, "parser_replay_mismatches", errors)

    observed_counts = {name: len(rows) for name, rows in loaded.items()}
    require(observed_counts == expected["record_counts"], f"record_counts:{observed_counts}", errors)
    claim_rows = populations["E1"]["records"] + populations["E2"]["claim_bearing_branch_rows"] + populations["F1"]["claim_bearing_branch_rows"] + populations["F0"]["claim_bearing_branch_rows"] + populations["QWEN37"]["claim_bearing_branch_rows"]
    require(claim_rows == expected["claim_bearing_evidence_rows"], f"claim_rows:{claim_rows}", errors)
    actual_calls = populations["E1"]["planned_calls"] + populations["E2"]["actual_calls"] + populations["F1"]["planned_and_actual_calls"] + populations["F0"]["planned_and_actual_calls"] + populations["QWEN37"]["planned_and_actual_calls"]
    require(actual_calls == expected["saved_provider_calls"], f"saved_calls:{actual_calls}", errors)
    dual_replay_rows = sum(item["rows"] for item in comparisons.values())
    require(dual_replay_rows == expected["dual_replay_comparison_rows"], f"dual_replay_rows:{dual_replay_rows}", errors)

    status = "PASS" if not errors else "HOLD"
    report = {
        "schema_version": "state_grounding_public_vcr_h5e5_v1",
        "status": status,
        "vcr": {
            "status": status,
            "definition": "Saved provider outputs are replay inputs; every released record is checked against the public record manifest, retained task/prompt/request/parsed hashes are checked, and all successful response strings are independently re-parsed with the archived parser source.",
            "release_hash_map": release_map,
            "saved_provider_calls": actual_calls,
            "structured_skips": populations["E2"]["structured_skips"],
            "successful_saved_responses_reparsed": parser_replay.get("successful_responses_reparsed"),
            "parser_replay_mismatches": parser_replay.get("parsed_object_mismatches"),
        },
        "h5": {
            "status": status,
            "definition": "Claim-bearing rows retain task, prompt/request, raw response or explicit skip, parsed action, score/replay fields, comparison identity, timestamps, and hashes.",
            "claim_bearing_evidence_rows": claim_rows,
            "populations": populations,
        },
        "e5": {
            "status": status,
            "definition": "The frozen environment regenerates deterministic replay, score, comparisons, sensitivities, and tables; independent replay and physics checks show zero disagreement.",
            "dual_replay": comparisons,
            "dual_replay_comparison_rows": dual_replay_rows,
            "independent_physics_rows": physics.get("rows"),
            "independent_physics_discrepancies": physics.get("discrepancies"),
            "release_acceptance": acceptance.get("status"),
        },
        "boundaries": [
            "Provider calls are not rerun; VCR replays saved responses offline.",
            "E2 projection evidence retains 53/1800 timeouts and remains partial with timeouts.",
        ],
        "provider_calls_performed": 0,
        "network_attempts": 0,
        "errors": errors,
    }
    output.mkdir(parents=True, exist_ok=True)
    (output / "VCR_H5E5_VERIFICATION.json").write_text(
        json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    markdown = [
        "# VCR and H5/E5 verification",
        "",
        f"- Status: **{status}**",
        f"- Public record/block files: {sum(observed_counts.values())}",
        f"- Claim-bearing evidence rows: {claim_rows}",
        f"- Saved provider calls represented: {actual_calls}",
        f"- Successful saved responses independently re-parsed: {parser_replay.get('successful_responses_reparsed')}",
        f"- Parser-replay mismatches: {parser_replay.get('parsed_object_mismatches')}",
        f"- Dual-replay comparison rows: {dual_replay_rows}",
        f"- Independent physics verdicts: {physics.get('rows')}",
        f"- Independent physics discrepancies: {physics.get('discrepancies')}",
        "- Provider calls performed by verifier: 0",
        "- Network attempts: 0",
        "",
        "The verifier replays saved responses only. It does not contact any provider.",
    ]
    (output / "VCR_H5E5_VERIFICATION.md").write_text(
        "\n".join(markdown) + "\n", encoding="utf-8"
    )
    print(json.dumps({"status": status, "claim_rows": claim_rows, "saved_calls": actual_calls, "dual_replay_rows": dual_replay_rows, "provider_calls": 0, "network_attempts": 0}, sort_keys=True))
    return 0 if status == "PASS" else 1


if __name__ == "__main__":
    raise SystemExit(main())
